### ISSUE TITLE
Cardreader without numpad errors

### ISSUE THREAD

**Issue by exolyte** [roelderickx/connective-plugin-linux#19]
I'm using a `ACS ACR38U 00 00` cardreader and was getting the following error when trying to run commands that require pin authentication: `stderr output from native app com.connective.signer: Failed to control Feature not supported.`

I tracked the issue down to this function call `features = self._connection.control(smartcard.scard.SCARD_CTL_CODE(3400), [])` which is part of the `smartcard` library if I understand correctly.

I commented out [self.__get_reader_features()](https://github.com/roelderickx/connective-plugin-linux/blob/7b13769adf1f228f1749456171b8e24da68142e7/connective-backend.py#L483) and L511-530 and the commands worked just fine.

Since it started working I didn't really dig any deeper and I'm not sure if there's anything to fix for you, but I figured this might help some people.

**Comment by roelderickx** [comment]
Thanks for your report and glad to see you were able to work around the issue.

The part you commented is the test to detect if there is a numeric keypad on your cardreader or not. Your modification always shows the keypad on screen, which is a great default if the capabilities cannot be detected.

I'll modify it that way, but since it is not urgent it may take some time.

**Comment by roelderickx** [comment]
I added extra error handling but I didn't disable lines 511-530, that code will be skipped if the detection flags are all set to False.
