### ISSUE TITLE
An error occured while handling your request

### ISSUE THREAD

**Issue by OnUrMarx** [roelderickx/connective-plugin-linux#24]
Hello,
I tried using this workaround to be able to use connective signing on ubuntu. I think I have managed to install correctly the extension since the protocoltest in browser returns no errors on the different demands. Except on the Maestro ones which returns these messages (but it's reading an id card so I brushed it off as normal since it's not a Maestro card) :

`Request sent: {"cmd":"SELECT_MAESTRO","reader":"VASCO DP905v1.1 00 00","activationToken":"","isRequest":true}
  Response received: {"error":{"code":99,"id":99,"message":"error calling SCardConnect (0x80100069) (0x0)"},"resp":"SELECT_MAESTRO"}`
`Request sent: {"cmd":"GET_PROCESSING_OPTIONS","reader":"VASCO DP905v1.1 00 00","activationToken":"","data":"8300","isRequest":true}
  Response received: {"error":{"code":99,"id":99,"message":"error calling SCardConnect (0x80100069) (0x0)"},"resp":"GET_PROCESSING_OPTIONS"}`
`Request sent: {"cmd":"READ_RECORD","reader":"VASCO DP905v1.1 00 00","activationToken":"","record":"01","sfi":"02","isRequest":true}
  Response received: {"error":{"code":99,"id":99,"message":"error calling SCardConnect (0x80100069) (0x0)"},"resp":"READ_RECORD"}`

However, when trying to connect to the card on Itsme, these messages appear on the browser page and afterwards displays "an error occured while handling your request"
"Connect a card reader and insert a valid ID
  Reading personal information
  Reading address information (doesn't always appear)"

Does someone have any idea what could be the issue ?
Regards,

**Comment by roelderickx** [comment]
Hi,

The maestro functions were never fully tested and I doubt they are used in production. As far as I can see you have installed everything correctly, since 'Reading personal information' does work sometimes.

It looks a bit like the issue with [the Alcor Micro AU9540](https://github.com/roelderickx/connective-plugin-linux/issues/18#issuecomment-1925402112), however that device is unsupported while the Vasco DP905 v1.1 [should work](https://ccid.apdu.fr/ccid/shouldwork.html#0x1A440x0001).

Can you have a look at the debug messages? For firefox you have to press ctrl-shift-J, for chrome / chromium you have to start the browser from a terminal window. Then try to register the itsme account and look at the output.

If you post the output here, make sure to remove your personal data, found on lines which look like this:
```
stderr output from native app com.connective.signer: OUT {"data": "..."}
```
